In [1]:
import torch
import numpy as np

设置能够自动求导

In [40]:
x = torch.rand(5,3, requires_grad=True)
x

tensor([[0.5378, 0.9713, 0.9915],
        [0.6953, 0.1794, 0.6824],
        [0.0900, 0.0731, 0.4603],
        [0.3129, 0.9696, 0.3469],
        [0.1877, 0.4421, 0.4036]], requires_grad=True)

In [41]:
y = torch.randn(5,3,requires_grad=True)
y

tensor([[ 1.3524, -0.3126,  1.3988],
        [ 0.1042, -0.3771,  2.4276],
        [ 0.2265, -1.0495, -0.0255],
        [ 0.3947, -0.4386,  0.5123],
        [ 0.2049,  0.1801, -0.2465]], requires_grad=True)

In [42]:
z = 2*x + y
t = z.sum()

进行一次backward之后，各个节点的值会清除，这样进行第二次backward会报错，如果加上retain_graph==True后,可以再来一次backward。
如果设置为False，计算图中的中间变量在计算完后就会被释放。但是在平时的使用中这个参数默认都为False从而提高效率，和creat_graph的值一样。

In [45]:
t.backward()

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.

In [44]:
y.grad

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])