In [2]:
import torch

In [3]:
import numpy as np

In [4]:
torch.__version__

'1.8.1+cu101'

初始化一个随机矩阵

In [5]:
x = torch.rand(5,3)
x

tensor([[0.3268, 0.2111, 0.7256],
        [0.4062, 0.0046, 0.4451],
        [0.2291, 0.2070, 0.8400],
        [0.1830, 0.7143, 0.0461],
        [0.4515, 0.1675, 0.8874]])

初始化一个全零矩阵

In [10]:
x = torch.zeros(5,3, dtype=torch.int)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

直接传值

In [14]:
x = torch.tensor([5,3])
x

tensor([5, 3])

将x重新变为另一维度的矩阵

In [24]:
x = x.new_ones(4,2)
x

tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]])

查看x的维度

In [25]:
x.shape,x.size()

(torch.Size([4, 2]), torch.Size([4, 2]))

In [30]:
x = torch.rand(4,2)
y = torch.rand(4,2)
x,y

(tensor([[0.3276, 0.4154],
         [0.9735, 0.0628],
         [0.4171, 0.5247],
         [0.1429, 0.5853]]),
 tensor([[0.2035, 0.1065],
         [0.3965, 0.4592],
         [0.6061, 0.8984],
         [0.3299, 0.1395]]))

In [31]:
z1 = x + y
z2 = torch.add(x, y)
z1, z2

(tensor([[0.5310, 0.5220],
         [1.3700, 0.5220],
         [1.0232, 1.4231],
         [0.4728, 0.7248]]),
 tensor([[0.5310, 0.5220],
         [1.3700, 0.5220],
         [1.0232, 1.4231],
         [0.4728, 0.7248]]))

In [33]:
y = x.view(8)
y

tensor([0.3276, 0.4154, 0.9735, 0.0628, 0.4171, 0.5247, 0.1429, 0.5853])